name: AETHRA OS 16 - Lavender
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - run: |
          sudo rm -rf /usr/share/dotnet /opt/ghc
          sudo apt-get update
          sudo apt-get install -y repo git curl
          mkdir -p ~/bin
          curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
          chmod a+x ~/bin/repo
          echo "$HOME/bin" >> $GITHUB_PATH
      - run: |
          mkdir aethra && cd aethra
          repo init -u https://github.com/ProjectInfinity-X/manifest -b 16 --depth=1
          repo sync -c -j2 --no-tags -q
          source build/envsetup.sh
          lunch infinity_lavender-userdebug
          m bacon -j2
      - uses: actions/upload-artifact@v4
        with:
          name: AETHRA-OS-16
          path: aethra/out/target/product/lavender/*.zip
