name: AETHRA OS Build
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          echo "AETHRA OS by Otodidak07"
          mkdir out
          echo "AETHRA ready" > out/info.txt
      - uses: actions/upload-artifact@v4
        with:
          name: AETHRA-OS
          path: out/
